FROM golang:1.23-alpine

WORKDIR /app

# Install air for hot reloading and other dependencies
RUN go install github.com/air-verse/air@v1.61.4 && \
    apk add --no-cache gcc musl-dev

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Expose port
EXPOSE 8080

# Use air for hot reloading in development
CMD ["air"]